myOJ/OJ/urls.py
from django.urls import path

from . import views

app_name = 'OJ'

urlpatterns = [
    path('problems/',views.problems, name='problem'),
    path('problem/<str:question_name>',views.problem_details,name='problem_details'),
    path("register", views.register_request, name="register"),
    path("login",views.login_request,name="login"),
    path('leaderboard',views.user_submission,name='user_submission'),
    path('',views.user_logout,name='logout'),
]

myOJ/myOJ/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('OJ/', include('OJ.urls')),
    path('admin/', admin.site.urls),
]

myOJ/OJ/models.py
from decimal import DefaultContext
from django.db import models
from django.forms import CharField
from django.contrib.auth.models import User
from django.utils.timezone import now
class Problem(models.Model):
    prob_name = models.CharField(max_length=100)
    prob_desc = models.CharField(max_length=10000)
    prob_diff = models.CharField(max_length=50)
    score = models.FloatField(default=0) 

    def __str__(self):
        return self.prob_name 

class Test_cases(models.Model):
    probId = models.ForeignKey(Problem,on_delete=models.CASCADE)
    input = models.CharField(max_length=10000)
    output = models.CharField(max_length=10000)

    def __str__(self):
        return self.input

class Submission(models.Model):
    user_Id = models.ForeignKey(User,on_delete=models.CASCADE)
    probId = models.ForeignKey(Problem,on_delete=models.CASCADE)
    timestrap = models.DateTimeField(default=now)
    verdict = models.CharField(max_length=10,default='NOT SOLVED')

class User_score(models.Model):
    user_Id = models.OneToOneField(User, on_delete=models.CASCADE,primary_key=True)
    score = models.FloatField(default=0)

myOJ/OJ/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SubmitedCode(forms.Form):
   solution = forms.CharField(widget=forms.Textarea)

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

myOJ/OJ/views.py
from datetime import datetime
from json import load
from multiprocessing import context
from re import template
from unittest import loader
from django.shortcuts import render,redirect,get_object_or_404, render
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.template import loader
from .forms import SubmitedCode
from .compilingFunc import compiler
from .forms import NewUserForm
from django.contrib.auth import login,authenticate,logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist

from .models import Problem,Test_cases,Submission, User_score

def problems(request):
    problem_list = Problem.objects.all()
    template = loader.get_template('OJ/problems.html')
    score = User_score.objects.get(pk = request.user.id).score
    context = {'problem_list': problem_list,'score':score}
    return HttpResponse(template.render(context,request))

def problem_details(request, question_name):
    problem = get_object_or_404(Problem,prob_name=question_name)
    if request.method == 'POST':
        form = SubmitedCode(request.POST)
        if form.is_valid():
            code = form.cleaned_data['solution']
            # testcases = Test_cases.objects.filter(probId=problem.pk)
            # print(testcases)
            # if(compiler(code)):
            #     print("accepted")
            # else:
            #     print("Wrong Answer")
            # print(compiler(code,problem.pk))
            # print(request.user.username)
            # user = User.objects.get()
            submission = Submission()
            submission.user_Id = request.user
            submission.probId = problem
            # submission.timestrap = datetime.now
            submission.verdict = compiler(code,problem.pk)    
            submission.save()
            try: 
                userscore =User_score.objects.get(user_Id__pk= request.user.id )
                userscore.score = userscore.score + problem.score
                userscore.save()
            except:
                userscore = User_score(user_Id=request.user,score = problem.score)    
                userscore.save()
    else:
        form = SubmitedCode()
    template = loader.get_template('OJ/detail.html')
    context = {'problem':problem,'form':form}
    return HttpResponse(template.render(context,request))

def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful." )
            return redirect("OJ:problem")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()
    return render (request=request, template_name="OJ/register.html", context={"register_form":form})


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, "You are now logged in as {username}.")
                return redirect('OJ:problem')
            else:
                messages.error(request,"Invalid username or password.")
        else:
            messages.error(request,"Invalid username or password.")
    form = AuthenticationForm()
    return render(request=request, template_name="OJ/login.html", context={"login_form":form})

def user_submission(request):
    submission_list = Submission.objects.filter(user_Id =request.user)

    template = loader.get_template('OJ/submission.html')
    context = {'submission_list': submission_list}
    return HttpResponse(template.render(context,request))
    
def user_logout(request):
    logout(request)
    return redirect('OJ:login')

myOJ/OJ/templates/OJ/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>My Project</title>
    </head>

    <body>
    {% block content %}{% endblock content %}
    </body>
</html>

myOJ/OJ/templates/OJ/detail.html
<html>
<head>
	      <!-- Required meta tags -->
		  <meta charset="utf-8">
		  <meta name="viewport" content="width=device-width, initial-scale=1">
	  
		  <!-- Bootstrap CSS -->
		  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
			  integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	  
		  <title>Problems</title>
		  <style>
			  body {
				  background-color: #262626;
			  }
			  .links_tag{
				  color: cyan !important;
				  font-size: x-large !important;
			  }
		  
			  .list {
				  color: aquamarine; 
			  }
			  .links {
				  padding: 10px 25px 10px 5px;   
			  }
			  .indexing{
				  padding: 0px;  
			  }
		  
			  .list tbody tr td a {
				  text-decoration: none;
				  color: aquamarine;
			  }
		  
			  .list tbody tr td a:hover {
				  text-decoration: underline;
			  }
			  
		  </style>
	  </head>
	
	
	
	  <div class="user_info">
		  {% if user.is_authenticated %}
		  <nav class="navbar navbar-light navbar-expand-md bg-dark justify-content-center">
			  <div class="container">
				  <a href="#" class="navbar-brand d-flex w-50 me-auto links_tag">Hi, {{user.username}} </a>
				  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsingNavbar3">
					  <span class="navbar-toggler-icon"></span>
				  </button>
				  <div class="navbar-collapse collapse w-100" id="collapsingNavbar3">
					  <ul class="navbar-nav w-100 justify-content-center">
						  <li class="nav-item active">
							  <a class="nav-link links_tag" href="{% url 'OJ:problem' %}">Problems</a>
						  </li>
						  <li class="nav-item">
							  <a class="nav-link links_tag" href="{% url 'OJ:user_submission' %}">Submissions</a>
						  </li>
					  </ul>
					  <ul class="nav navbar-nav ms-auto w-100 justify-content-end">
						  <li class="nav-item">
							  <a class="nav-link links_tag" href="{% url 'OJ:logout' %}">Logout</a>
						  </li>
					  </ul>
				  </div>
			  </div>
		  </nav>
		  {% else %}
		  <nav class="navbar navbar-light navbar-expand-md bg-dark justify-content-center">
			  <div class="container">
				  <a href="#" class="navbar-brand d-flex w-50 me-auto links_tag">Hi, you are not logged in. Please login</a>
				  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsingNavbar3">
					  <span class="navbar-toggler-icon"></span>
				  </button>
				  <div class="navbar-collapse collapse w-100" id="collapsingNavbar3">
					  <ul class="navbar-nav w-100 justify-content-center">
						  <li class="nav-item active">
							  <a class="nav-link links_tag" href="{% url 'OJ:problem' %}">Problems</a>
						  </li>
						  <li class="nav-item">
							  <a class="nav-link links_tag" href="{% url 'OJ:register' %}">Register</a>
						  </li>
					  </ul>
					  <ul class="nav navbar-nav ms-auto w-100 justify-content-end">
						  <li class="nav-item">
							  <a class="nav-link links_tag" href="{% url 'OJ:login' %}">Login</a>
						  </li>
					  </ul>
				  </div>
			  </div>
		  </nav>
		  {% endif %}
	  </div>
	<!-- <p><a href="{% url 'OJ:logout' %}">Log Out</a></p> -->
<title>{% if problem %} {{problem.prob_name}} {% endif %}</title>
</head>
<body>
	<div class="container_p" style="color:red;">
{% if problem %}
	<h1>{{problem.prob_name}}</h1><br/>
	<p>{{problem.prob_desc}}</p><br/>
	<form  method="POST">
		{{form.as_p}}
	{% csrf_token %}
	<input type="submit" value="Upload">
	</form>
</div>
{% endif %}
<li><a href="{% url 'OJ:user_submission' %}">SUBMISSION PAGE</a></li> 


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
crossorigin="anonymous"></script>
</body>
</html>

myOJ/OJ/templates/OJ/login.html
<!-- <!DOCTYPE html>
<html>
    <head>
        <title>My Project</title>
    </head>

    <body>
    {% block content %}
    <div class="container py-5">
        <h1>Login</h1>
        <form method="POST">
          {% csrf_token %}
          {{ login_form }}
          <button class="btn btn-primary" type="submit">Login</button>
        </form>
        <p class="text-center">Don't have an account? <a href="/register">Create an account</a>.</p>
      </div>
    
    {% endblock content %}
    </body>
</html> -->


<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Design by foolishdeveloper.com -->
    <title>Glassmorphism login Form Tutorial in html css</title>
 
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
    <!--Stylesheet-->
    <style media="screen">
      *,
*:before,
*:after{
    padding: 0;
    margin: 0;
    box-sizing: border-box;
}
body{
    background-color: #080710;
}
.background{
    width: 430px;
    height: 520px;
    position: absolute;
    transform: translate(-50%,-50%);
    left: 50%;
    top: 50%;
}
.background .shape{
    height: 200px;
    width: 200px;
    position: absolute;
    border-radius: 50%;
}
.shape:first-child{
    background: linear-gradient(
        #1845ad,
        #23a2f6
    );
    left: -80px;
    top: -80px;
}
.shape:last-child{
    background: linear-gradient(
        to right,
        #ff512f,
        #f09819
    );
    right: -30px;
    bottom: -80px;
}
form{
    height: 520px;
    width: 400px;
    background-color: rgba(255,255,255,0.13);
    position: absolute;
    transform: translate(-50%,-50%);
    top: 50%;
    left: 50%;
    border-radius: 10px;
    backdrop-filter: blur(10px);
    border: 2px solid rgba(255,255,255,0.1);
    box-shadow: 0 0 40px rgba(8,7,16,0.6);
    padding: 50px 35px;
}
form *{
    font-family: 'Poppins',sans-serif;
    color: #ffffff;
    letter-spacing: 0.5px;
    outline: none;
    border: none;
}
form h3{
    font-size: 32px;
    font-weight: 500;
    line-height: 42px;
    text-align: center;
}

label{
    display: block;
    margin-top: 30px;
    font-size: 16px;
    font-weight: 500;
}
input{
    display: block;
    height: 50px;
    width: 100%;
    background-color: rgba(255,255,255,0.07);
    border-radius: 3px;
    padding: 0 10px;
    margin-top: 8px;
    font-size: 14px;
    font-weight: 300;
}
::placeholder{
    color: #e5e5e5;
}
button{
    margin-top: 50px;
    width: 100%;
    background-color: #ffffff;
    color: #080710;
    padding: 15px 0;
    font-size: 18px;
    font-weight: 600;
    border-radius: 5px;
    cursor: pointer;
}
.social{
  margin-top: 30px;
  display: flex;
}
.social div{
  background: red;
  width: 150px;
  border-radius: 3px;
  padding: 5px 10px 10px 5px;
  background-color: rgba(255,255,255,0.27);
  color: #eaf0fb;
  text-align: center;
}
.social div:hover{
  background-color: rgba(255,255,255,0.47);
}
.social .fb{
  margin-left: 25px;
}
.social i{
  margin-right: 4px;
}

    </style>
</head>
<body>
    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>
    <form method="POST">
      {% csrf_token %}
        <h3>Login Here</h3>

        <label for="username">Username</label>
        <!-- <input type="text" placeholder="Email or Phone" id="username"> -->
        {{login_form.username}}
        <label for="password">Password</label>
        <!-- <input type="password" placeholder="Password" id="password"> -->
        {{login_form.password}}
        <button>Log In</button>
        <div class="social">
          <div class="go"><i class="fab fa-google"></i>  Google</div>
          <div class="fb"><i class="fab fa-facebook"></i>  Facebook</div>
        </div>
    </form>
</body>
</html>

myOJ/OJ/templates/OJ/problems.html
{%load static%}

<html>
<head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
  
      <!-- Bootstrap CSS -->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  
      <title>Problems</title>
      <style>
          body {
              background-color: #262626;
          }
          .links_tag{
              color: cyan !important;
              font-size: x-large !important;
          }
      
          .list {
              color: aquamarine; 
          }
          .links {
              padding: 10px 25px 10px 5px;   
          }
          .indexing{
              padding: 0px;  
          }
      
          .list tbody tr td a {
              text-decoration: none;
              color: aquamarine;
          }
      
          .list tbody tr td a:hover {
              text-decoration: underline;
          }
          
      </style>
  </head>


<body>
  <div class="user_info">
      {% if user.is_authenticated %}
      <nav class="navbar navbar-light navbar-expand-md bg-dark justify-content-center">
          <div class="container">
              <a href="#" class="navbar-brand d-flex w-50 me-auto links_tag">Hi, {{user.username}} Your Score is {{score}}</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsingNavbar3">
                  <span class="navbar-toggler-icon"></span>
              </button>
              <div class="navbar-collapse collapse w-100" id="collapsingNavbar3">
                  <ul class="navbar-nav w-100 justify-content-center">
                      <li class="nav-item active">
                          <a class="nav-link links_tag" href="{% url 'OJ:problem' %}">Problems</a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link links_tag" href="{% url 'OJ:user_submission' %}">Submissions</a>
                      </li>
                  </ul>
                  <ul class="nav navbar-nav ms-auto w-100 justify-content-end">
                      <li class="nav-item">
                          <a class="nav-link links_tag" href="{% url 'OJ:logout' %}">Logout</a>
                      </li>
                  </ul>
              </div>
          </div>
      </nav>
      {% else %}
      <nav class="navbar navbar-light navbar-expand-md bg-dark justify-content-center">
          <div class="container">
              <a href="#" class="navbar-brand d-flex w-50 me-auto links_tag">Hi, you are not logged in. Please login</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsingNavbar3">
                  <span class="navbar-toggler-icon"></span>
              </button>
              <div class="navbar-collapse collapse w-100" id="collapsingNavbar3">
                  <ul class="navbar-nav w-100 justify-content-center">
                      <li class="nav-item active">
                          <a class="nav-link links_tag" href="{% url 'OJ:problem' %}">Problems</a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link links_tag" href="{% url 'OJ:register' %}">Register</a>
                      </li>
                  </ul>
                  <ul class="nav navbar-nav ms-auto w-100 justify-content-end">
                      <li class="nav-item">
                          <a class="nav-link links_tag" href="{% url 'OJ:login' %}">Login</a>
                      </li>
                  </ul>
              </div>
          </div>
      </nav>
      {% endif %}
  </div>
  <div class="listofproblem" style="display: flex;flex-direction: column; align-items: center;font-size: x-large">
      <h3 style="color: aliceblue;padding-top: 30px;">
          <u>Problem List!</u>
      </h3>
      <br>
      {% if problem_list %}
      <table class="list">
          {% for problem in problem_list %}
          <tbody>
              <tr>
                  <td class="indexing">{{forloop.counter}})</td>
                  <td class="links"> <a href="{% url 'OJ:problem_details' problem.prob_name %}">{{ problem.prob_name }}</a>
     
                      </a></td>
                  <!-- <td class="links">{{problems.problem_level}}</td> -->
              </tr>
          </tbody>
          {% endfor %}
      </table>
      {% else %}
      <p>No questions are available.</p>
      {% endif %}
  </div>

  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"></script>

  <!-- Option 2: Separate Popper and Bootstrap JS -->

  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
      integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
      crossorigin="anonymous"></script>
</body>
</html>>

myOJ/OJ/templates/OJ/submission.html
{%load static%}

<html>
<head>
  	      <!-- Required meta tags -->
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1">
        
          <!-- Bootstrap CSS -->
          <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        
          <title>Problems</title>
          <style>
            body {
              background-color: #262626;
            }
            .links_tag{
              color: cyan !important;
              font-size: x-large !important;
            }
          
            .list {
              color: aquamarine; 
            }
            .links {
              padding: 10px 25px 10px 5px;   
            }
            .indexing{
              padding: 0px;  
            }
          
            .list tbody tr td a {
              text-decoration: none;
              color: aquamarine;
            }
          
            .list tbody tr td a:hover {
              text-decoration: underline;
            }
            
          </style>
        </head>
      
      
      
        <div class="user_info">
          {% if user.is_authenticated %}
          <nav class="navbar navbar-light navbar-expand-md bg-dark justify-content-center">
            <div class="container">
              <a href="#" class="navbar-brand d-flex w-50 me-auto links_tag">Hi, {{user.username}} </a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsingNavbar3">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="navbar-collapse collapse w-100" id="collapsingNavbar3">
                <ul class="navbar-nav w-100 justify-content-center">
                  <li class="nav-item active">
                    <a class="nav-link links_tag" href="{% url 'OJ:problem' %}">Problems</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link links_tag" href="{% url 'OJ:user_submission' %}">Submissions</a>
                  </li>
                </ul>
                <ul class="nav navbar-nav ms-auto w-100 justify-content-end">
                  <li class="nav-item">
                    <a class="nav-link links_tag" href="{% url 'OJ:logout' %}">Logout</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
          {% else %}
          <nav class="navbar navbar-light navbar-expand-md bg-dark justify-content-center">
            <div class="container">
              <a href="#" class="navbar-brand d-flex w-50 me-auto links_tag">Hi, you are not logged in. Please login</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsingNavbar3">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="navbar-collapse collapse w-100" id="collapsingNavbar3">
                <ul class="navbar-nav w-100 justify-content-center">
                  <li class="nav-item active">
                    <a class="nav-link links_tag" href="{% url 'OJ:problem' %}">Problems</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link links_tag" href="{% url 'OJ:register' %}">Register</a>
                  </li>
                </ul>
                <ul class="nav navbar-nav ms-auto w-100 justify-content-end">
                  <li class="nav-item">
                    <a class="nav-link links_tag" href="{% url 'OJ:login' %}">Login</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
          {% endif %}
    <title>Your Submitted Problem</title>>
</head>
<body>
  <div class="listofproblem" style=" color:blue; display: flex;flex-direction: column; align-items: center;font-size: x-large;">
    {%if submission_list%}
    <ul>
        <table style="color:aqua">
            <tr>
                <th>Problem ID</th>
                <th>Time</th>
                <th>Verdict</th>
              </tr>
            {%for submission in submission_list%}
            <tr>
              <th>{{submission.probId.prob_name}}</th>
              <th>{{submission.timestrap}}</th>
              <th>{{submission.verdict}}</th>
            </tr>
            {% endfor %}
          </table>
    </ul> 
    {% else %}
    <p>You have not Submitted anything</p>
{% endif %}   
  </div>
</body>
  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"></script>

  <!-- Option 2: Separate Popper and Bootstrap JS -->

  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
      integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
      crossorigin="anonymous"></script>
</html>